name: CI Pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install modules
        run: npm ci --force
      - name: Run ESLint
        run: npm run eslint:run
      - name: Run Prettier
        run: npm run prettier:check
      - name: Build
        run: npm run build
